site_name: K8s-Gen DSL Documentation
site_url: https://your-username.github.io/k8s-gen/
site_description: A modern Python DSL for generating Kubernetes manifests, Helm charts, and more
site_author: K8s-Gen Team

# Repository
repo_url: https://github.com/sps014/k8s-gen
repo_name: sps014/k8s-gen
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2024 K8s-Gen Contributors

# Configuration
theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - navigation.indexes
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - content.code.copy
    - content.code.annotate
    - content.action.edit
    - content.action.view
  palette:
    # Palette toggle for dark mode (default)
    - scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: default
      primary: teal
      accent: cyan
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: material/kubernetes
    repo: fontawesome/brands/github

# Plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - awesome-pages
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: true
            show_root_heading: true
            show_root_full_path: false
            show_object_full_path: false
            show_category_heading: true
            group_by_category: true
            heading_level: 2
  - mermaid2:
      arguments:
        theme: auto

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: sps014
      repo: k8s-gen
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Home: index.md
  - Getting Started:
    - getting-started/index.md
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quick-start.md
    - Core Concepts: getting-started/core-concepts.md
    - Your First App: getting-started/first-app.md
  - Components:
    - components/index.md
    - Core Components:
      - Application: components/core/app.md
      - Stateful Application: components/core/stateful-app.md
      - Application Group: components/core/app-group.md
    - Workloads:
      - Job: components/workloads/job.md
      - Cron Job: components/workloads/cron-job.md
    - Networking:
      - Service: components/networking/service.md
      - Ingress: components/networking/ingress.md
    - Security:
      - RBAC: components/security/rbac.md
      - Secrets: components/security/secrets.md
    - Storage:
      - ConfigMap: components/storage/config-map.md
  - Tutorials:
    - tutorials/index.md
    - Basic Web App: tutorials/basic-web-app.md
    - RBAC Security: tutorials/rbac-security.md
    - Microservices Platform: tutorials/microservices.md
    - WordPress Platform: tutorials/wordpress-platform.md
    - Multi-Environment: tutorials/multi-environment.md
    - Kafka Deployment: tutorials/kafka-deployment.md
    - Observability Stack: tutorials/observability-stack.md
  - Examples:
    - examples/index.md
    - Messaging:
      - Kafka: examples/messaging/kafka.md
  - API Reference:
    - api-reference/index.md
  - Configuration:
    - configuration/index.md
  - Advanced:
    - advanced/index.md

# Extra
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sps014/k8s-gen
  version:
    provider: mike 