site_name: Celestra Documentation
site_description: Complete guide for Celestra - Kubernetes DSL
site_author: Celestra Team
site_url: https://celestra.dev

repo_name: sps014/Celestra
repo_url: https://github.com/sps014/Celestra
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - navigation.tracking
    - content.action.edit
    - content.action.view
    - header.autohide
    - toc.follow
    - toc.integrate
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    # Dark mode (default)
    - scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/copy-code.js

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
      title: On this page
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search:
      lang: en
      separator: '[\s\-,:!=\[\]()"/`|]+'
      prebuild_index: true
      indexing: full

nav:
  - Home: index.md
  - Getting Started:
      - Quick Start: getting-started/quick-start.md
      - Installation: getting-started/installation.md
      - Core Concepts: getting-started/core-concepts.md
  - Components:
      - App: components/core/app.md
      - StatefulApp: components/core/stateful-app.md
      - Service: components/networking/service.md
      - Ingress: components/networking/ingress.md
      - RBAC: components/security/rbac.md
      - Secrets: components/security/secrets.md
      - ConfigMap: components/storage/config-map.md
      - Deployment: components/workloads/deployment.md
      - Job: components/workloads/job.md
      - CronJob: components/workloads/cron-job.md
      - Observability: components/advanced/observability.md
      - Plugin System: components/advanced/plugin-system.md
  - Tutorials:
      - Kafka Deployment: tutorials/kafka-deployment.md
      - Multi-Environment: tutorials/multi-environment.md
      - Microservices: tutorials/microservices.md
      - Observability Stack: tutorials/observability-stack.md
  - Examples:
      - Hello World: examples/simple/hello-world.md
      - NGINX App: examples/simple/nginx-app.md
      - Node.js App: examples/simple/nodejs-app.md 